// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/Bo0mer/os-agent/server"
)

type FakeRequest struct {
	BodyStub        func() []byte
	bodyMutex       sync.RWMutex
	bodyArgsForCall []struct{}
	bodyReturns     struct {
		result1 []byte
	}
}

func (fake *FakeRequest) Body() []byte {
	fake.bodyMutex.Lock()
	fake.bodyArgsForCall = append(fake.bodyArgsForCall, struct{}{})
	fake.bodyMutex.Unlock()
	if fake.BodyStub != nil {
		return fake.BodyStub()
	} else {
		return fake.bodyReturns.result1
	}
}

func (fake *FakeRequest) BodyCallCount() int {
	fake.bodyMutex.RLock()
	defer fake.bodyMutex.RUnlock()
	return len(fake.bodyArgsForCall)
}

func (fake *FakeRequest) BodyReturns(result1 []byte) {
	fake.BodyStub = nil
	fake.bodyReturns = struct {
		result1 []byte
	}{result1}
}

var _ server.Request = new(FakeRequest)
